<a href="https://colab.research.google.com/github/readytocommit/FinalProject/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#When we train Deep Leatning models, randomness enters the process in few different places,

"""
Starting values for the weights (the optimizer will try to improve these weights)
The order in which we process minibatches when we do SGD
When we split the data into Train, Validation,Test etc
Droupout if we use regularization

We set seed for the different random number generators so that the results will be same every time the notebook is run.


"""

'\nStarting values for the weights (the optimizer will try to improve these weights)\nThe order in which we process minibatches when we do SGD\nWhen we split the data into Train, Validation,Test etc\nDroupout if we use regularization\n\nWe set seed for the different random number generators so that the results will be same every time the notebook is run.\n\n\n'

In [7]:
keras.utils.set_random_seed(42)

#Reading the data
file_url = file_url = "http://storage.googleapis.com/download.tensorflow.org/data/heart.csv"
df = pd.read_csv(file_url)

In [12]:
df.head()

   age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]

In [13]:
# Lets take a look if 1s and 0s are balaced or not.

df.target.value_counts(normalize=True,dropna= False)

target
0    0.726073
1    0.273927
Name: proportion, dtype: float64

In [14]:
# From the data we can see that 72 % dont have the heart dieases
# and only 27 % people have the heart disease.

# It is a bit imbalanced

# "Whats a naive baseline model for this problem ? "

# A baseline model would just predict a proabillity of 0.0 for every patient. That will result in 72.6% accuracy.
# Any fancy model we build needs to do better than this

In [22]:
#Preprocessing

# This dataset has both categorical variables and numeric variables.

# It will be convinient (for later processing) to collect these groups of variables into two lists

df.to_csv("data.csv")

print(df.head(n = 5))
print(df.shape)
print(df.columns)

#From the table we can see that

numerical_variables = ['age','trestbps','chol','thalach','']

   age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]
(303, 14)
Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')